version: '3.6'

services:
    myjenkins:
       build:
          context: ./
#          args:
#             - httpsPrivatKey=/var/lib/jenkins/privkey1.pem
#             - httpsCertificate=/var/lib/jenkins/fullchain1.pem
#             - httpsPort=8083
#             - httpPort=-1
#       depends_on:
#          - redis
#       target: prod
       restart: always
       ports:
          - target: 8080
            published: 9090
            protocol: tcp
            mode: host
#          - target: 8083
#            published: 9093
#            protocol: tcp
#            mode: host
          - target: 50000
            published: 50000
            protocol: tcp
            mode: host
       dns:
          - 172.31.0.2
       volumes:
          - type: bind
            source: /home/fedora/jenkins
            target: /var/jenkins_home
          - /etc/letsencrypt/live/fedora.shavitglobal.com/privkey.pem:/var/lib/jenkins/privkey1.pem
          - /etc/letsencrypt/live/fedora.shavitglobal.com/fullchain.pem:/var/lib/jenkins/fullchain1.pem
       environment:
          # Plugins upgrade
          - TRY_UPGRADE_IF_NO_MARKER=true
       healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9090"]
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 40s
